[package]
name = "day12"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_utils = { version = "0.1.0", path = "../aoc_utils" }
ndarray = "0.16.1"
rustc-hash = "2.1.1"

[dev-dependencies]
divan = "0.1.17"

[[bench]]
name = "benchmark"
harness = false
